# Generated by Django 3.1.7 on 2021-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_episode_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=models.CharField(default='https://share.transistor.fm/e/1493e91f/dark', max_length=200),
        ),
    ]
